---
title: "**Abstract**"
output: pdf_document
papersize: a4
---

Urbanized tropical estuaries in emerging countries are experiencing an imbalance between urbanization and water quality management practices. The lack of monitoring and modeling programs has not allowed understanding the dynamics of nutrients. This thesis aims to study nutrient dynamics in a tropical estuary under the influence of a megacity. Three specific objectives are (i) assessing the biogeochemical functioning of an urbanized tropical estuary (Saigon River Estuary, Vietnam) receiving wastewaters of Ho Chi Minh Megacity (HCMC); (ii) quantifying the role of controlling factors (e.g., nutrient loads, reaction rates, hydrological conditions) in the eutrophication development; (iii) assessing eutrophication risk under the scenarios of rapid urbanization and increased wastewater treatment capacity.

The Carbon-Generic Estuarine Model (C-GEM), a one-dimensional, reaction-transport model, was applied after calibration with the limited datasets existing in developing countries. The biogeochemical functioning was evaluated by analyzing monitoring data (physiochemical, phytoplankton structure and abundance, and greenhouse gases) and completed by the modeling approach. The C-GEM was calibrated and validated for Saigon River Estuary at steady-state in the dry season to evaluate the intensity of biogeochemical reactions. Dynamics of nutrients, phytoplankton, eutrophication were assessed by the transient version of C-GEM for 2017-2018. Statistical methods (e.g., Principal component analysis, Redundancy analysis and Hierarchical Partitioning) were applied to evaluate the contribution of environmental parameters to the responses of phytoplankton, eutrophication, greenhouse gases emissions. Finally, scenarios oriented towards megacity development were evaluated using C-GEM to assess the eutrophication risk.

The results of this thesis are presented in four parts, respectively. The first part identifies the impact of domestic wastewater of the megacity on the temporal-spatial variations of nutrients, phytoplankton, eutrophication and greenhouse gases. There was no statistically significant difference in nutrient pollutant concentrations between the dry season and rainy season. However, the phytoplankton abundance in the dry season is about 100 times higher than that in the rainy season. High concentrations of organic carbon and nutrients (nitrogen and phosphorus) have resulted in oxygen depletion and abundant phytoplankton formation in the urban area of the estuary. The second part explains the biogeochemical functioning of urbanized tropical estuaries with the support of C-GEM model (steady-state version). The key biogeochemical processes (i.e., nitrification, denitrification, primary production) are quantified. This estuary effectively removes nitrogen thanks to the strong nitrification and denitrification processes. The third part studies the seasonal variation of nutrients and phytoplankton under the strong fluctuations of hydrological conditions of tropical estuaries. Residence time is one of the most important controlling factors affecting phytoplankton biomass. Finally, the eutrophication risk assessment results based on megacity development show that an increase in the number of WWTPs still does not guarantee good water quality conditions of the estuary.

Applying the C-GEM model with minimal data source highlights biogeochemical processes and hydrological factors in nutrients and eutrophication dynamics in urbanized tropical estuaries. Thus, this study provides effective support for better management of eutrophication risks for developing countries.

\noindent _Keywords_: biogeochemical model; megacity; phytoplankton; Vietnam; tropical estuaries.

\newpage

```{=latex}
\hypertarget{résumé}{%
\chapter*{Résumé}\label{résumé}}
\thispagestyle{empty}

\adjustmtc
\markboth{Résumé}{}
```

Les estuaires tropicaux urbanisés des pays émergents connaissent un déséquilibre entre l’urbanisation et les pratiques de gestion de la qualité de l’eau. Le manque de programmes de suivi et de modélisation n’a pas permis de comprendre la dynamique des nutriments. Cette thèse vise à étudier la dynamique des nutriments dans un estuaire tropical sous l’influence d’une mégapole. Trois objectifs spécifiques sont (i) l’évaluation du fonctionnement biogéochimique d’un estuaire tropical urbanisé (estuaire de la rivière Saigon, Vietnam) recevant les eaux usées de la mégapole Ho Chi Minh (HCMC) ; (ii) la quantification du rôle des facteurs de contrôle (par exemple, les charges en nutriments, les taux de réaction, les conditions hydrologiques) dans le développement de l’eutrophisation ; (iii) l’évaluation du risque d’eutrophisation dans le cadre de scénarios d’urbanisation rapide et d’augmentation de la capacité de traitement des eaux usées. 

Le Carbon-Generic Estuarine Model (C-GEM), un modèle de transport réactif unidimensionnel, a été appliqué après calibration avec les ensembles de données limités existant dans les pays en développement. Le fonctionnement biogéochimique a été évalué en analysant les données de surveillance (physiochimie, structure et abondance du phytoplancton, et gaz à effet de serre) et complété par l’approche de modélisation. Le C-GEM a été calibré et validé pour l’estuaire de la rivière Saigon en régime permanent pendant la saison sèche afin d’évaluer l’intensité des réactions biogéochimiques. Les dynamiques des nutriments, du phytoplancton, de l’eutrophisation ont été évaluées par la version transitoire du C-GEM pour 2017-2018. Des méthodes statistiques (par exemple, l’analyse en composantes principales, l’analyse de redondance et le partitionnement hiérarchique) ont été appliquées pour évaluer la contribution des paramètres environnementaux aux réponses du phytoplancton, de l’eutrophisation, des émissions de gaz à effet de serre. Enfin, des scénarios orientés vers le développement des mégapoles ont été évalués à l’aide de C-GEM pour évaluer le risque d’eutrophisation. 

Les résultats de cette thèse sont présentés respectivement en quatre parties. La première partie identifie l’impact des eaux usées domestiques de la mégapole sur les variations spatio-temporelles des nutriments, du phytoplancton, de l’eutrophisation et des gaz à effet de serre. Il n’y avait pas de différence statistiquement significative dans les concentrations de polluants nutritifs entre la saison sèche et la saison des pluies. Cependant, l’abondance du phytoplancton pendant la saison sèche est environ 100 fois supérieure à celle de la saison des pluies. Les concentrations élevées de carbone organique et de nutriments (azote et phosphore) ont entraîné un appauvrissement en oxygène et la formation d’un phytoplancton abondant dans la zone urbaine de l’estuaire. La deuxième partie explique le fonctionnement biogéochimique des estuaires tropicaux urbanisés à l’aide du modèle C-GEM (version en régime permanent). Les processus biogéochimiques clés (i.e., la nitrification, la dénitrification, la production primaire) sont quantifiés. Cet estuaire élimine efficacement l’azote grâce aux forts processus de nitrification et de dénitrification. La troisième partie étudie la variation saisonnière des nutriments et du phytoplancton sous les fortes fluctuations des conditions hydrologiques des estuaires tropicaux. Le temps de résidence est l’un des plus importants facteurs de contrôle de la biomasse phytoplanctonique. Enfin, les résultats de l’évaluation du risque d’eutrophisation basée sur le développement des mégapoles montrent qu’une augmentation du nombre de STEP ne garantit toujours pas de bonnes conditions de qualité de l’eau de l’estuaire. 

L’application du modèle C-GEM avec une source de données minimale met en évidence les processus biogéochimiques et les facteurs hydrologiques dans la dynamique des nutriments et de l’eutrophisation dans les estuaires tropicaux urbanisés. Ainsi, cette étude fournit un support efficace pour une meilleure gestion des risques d’eutrophisation pour les pays en développement.

\noindent _Mots-clés_: modélisation biogéochimique; mégapole; phytoplancton; Vietnam; estuaires tropicaux.
